### ISSUE TITLE
Cannot find micromamba environment.

### ISSUE THREAD

**Issue by corporal9736** [corker/vscode-micromamba#3]
### Environment

1. `node -v`: v14.16.1
1. `npm -v`: 6.14.12
1. Operating system: ubuntu 18.04 arm64

### Prerequisite

I'm using ubuntu inside proot, which allows running linux on android. And I'm using vscode for arm 1.55.2

### Steps to Reproduce

ctrl shift p and enter Micromamba: activate environment

### Relevant Debug Info

no debug info showed.

### Expected Behavior

show a list of environments

### Actual Behavior

nothing happened. No hints like "activate failed".

I tried run Micromamba:create and the create process runned successfully. The new environment was created correctly. But the last step, which I think might be activate the new env failed.
My env folder was ~/micromamba/envs/ and my working folder was ~/works/program.

**Comment by corker** [comment]
Hi @corporal9736 thank you for reporting the issue. As I understand you use Linux terminal to create micromamba environments in your home directory and want to activate this environment in vscode. This case is not yet covered in the vscode extension but I'm going to look into this. Currently you could create an environment in VSCode and it will be activated. Then you could deactivate, activate or remove created environment. Environments are stored in .micromamba directory under the workspace root.

**Comment by corporal9736** [comment]
err... I tried create a folder called .micromamba and the folder tree is like 
programfolder
|__.micromamba
|   |__envs
|   |    |__dev(env name)
|   |__.gitignore
|__other files
now the plugin output "can't activate micromamba".
What should I do to fix this?

**Comment by corporal9736** [comment]
should I install the whole micromamba in the .micromamba?

**Comment by corker** [comment]
You don't need to install micromamba. When you run create environment command vscode-micromamba extension checks if micromamba executable is available in {workspaceRoot}/.micromamba/ directory and download the latest version if needed. Then extension search for environment.yml or environment-*.yml in the {workspaceRoot} directory and if there are more than one offers to choose which one to use to create an environment. When no environment.yml was found it offers a list of templates to create one. Then extension would create an environment using downloaded micromamba and selected environment.yml. So basically you should be able to start from an empty directory opened in VSCode

**Comment by corker** [comment]
Here is a video how it would look like
https://www.linkedin.com/posts/michaelborisov_dotnetcode-golang-python-activity-6759909518060093441--hi3

**Comment by corker** [comment]
Regarding this part
> I tried run Micromamba:create and the create process runned successfully. The new environment was created correctly. But the last step, which I think might be activate the new env failed.
My env folder was ~/micromamba/envs/ and my working folder was ~/works/program.

This is a bug and I'm going to fix it. Although I believe this should not prevent you from using activated environment from terminal

**Comment by corker** [comment]
Unfortunately, I can't reproduce the issue. Can I ask you to follow these steps and check if you have any problems:
1. Open an empty directory in vscode
2. From the command palette run micromamba: create new environment
3. Choose a template e.g. python
4. Wait until environment created
5. Close all terminals with trash button
6. Open a new terminal

This new terminal window should have the environment activated

**Comment by corker** [comment]
@corporal9736 please check version 0.1.6 - this one shows only commands available in the current context.
Should be easier to follow.

**Comment by corporal9736** [comment]
I might get the point:
In the video you post, the new env is established in just the test/.micromamba/envs
but when i use Micromamba:create the env is established in my env folder, which is ~/micromamba/envs but not under the folder I'm in. The .micromamba folder(under the folder I'm in) is established but just a .gitignore in it.
Another thing is that I have to set "terminal.integrated.shellArgs.linux" with "-i" in the code-workspace file, or I'll just get bash:command not found. I've done mamba init and changed my .bashrc. I don't konw why that happens.
I'm using the version 0.1.6.
Thank you a lot.

**Comment by corporal9736** [comment]
I tried change the MAMBA_ROOT_PREFIX in my .bashrc and the plugin can work now. But I think this is not the way you expect. There might still be something wrong.

**Comment by corporal9736** [comment]
I think I get the point!
The file mamba.sh in env_name/etc/profile.d isn't establish automatically. After I copy it from my micromamba folder the plugin run correctly.

**Comment by corker** [comment]
I think I've got the point. Basically I need to cover the case when micromamba is already in the PATH and MAMBA_ROOT_PREFIX is defined. I'll put it on my list
